# Generated by Django 4.2.10 on 2024-04-26 10:37

from django.db import migrations
import ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0069_gfk_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='asn',
            field=ipam.fields.ASNField(),
        ),
    ]
