# Generated by Django 4.2.10 on 2024-05-01 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0070_alter_asn_asn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='ip_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_range', to='ipam.iprange'),
        ),
    ]
