# Generated by Django 4.2.10 on 2024-05-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0072_remove_ipaddress_ip_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprange',
            name='addresses',
            field=models.ManyToManyField(related_name='ranges', to='ipam.ipaddress'),
        ),
    ]
