# Generated by Django 4.2.10 on 2024-05-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0073_iprange_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iprange',
            name='addresses',
        ),
    ]
