# Generated by Django 4.2.10 on 2024-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0076_remove_prefix_area_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='area_network',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
