# Generated by Django 4.2.10 on 2024-05-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0077_prefix_area_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='area_network',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
