# Generated by Django 4.2.10 on 2024-05-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0185_gfk_indexes'),
        ('ipam', '0078_alter_prefix_area_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='ipam_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefixes', to='dcim.region'),
        ),
    ]
