# Generated by Django 4.2.10 on 2024-05-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0079_prefix_ipam_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefix',
            name='ipam_region',
        ),
    ]
