# Generated by Django 4.2.10 on 2024-05-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0087_ipaddress_site_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='site_group',
        ),
    ]
