# Generated by Django 4.2.10 on 2024-05-27 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0185_gfk_indexes'),
        ('ipam', '0088_remove_ipaddress_site_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ip_addresses', to='dcim.sitegroup'),
        ),
    ]
