# Generated by Django 4.2.10 on 2024-05-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0089_ipaddress_territory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='territory',
        ),
    ]
